# Generated by Django 6.0.5 on 2026-05-15 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100)),
                ('manufacturer', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('NARROW', 'Narrow Body'), ('WIDE', 'Wide Body'), ('REGIONAL', 'Regional Jet'), ('TURBO', 'Turboprop')], max_length=20)),
                ('capacity_economy', models.IntegerField()),
                ('capacity_business', models.IntegerField(default=0)),
                ('capacity_first', models.IntegerField(default=0)),
                ('range_km', models.IntegerField(help_text='Maximum range in kilometers')),
                ('cruise_speed', models.IntegerField(help_text='Cruise speed in km/h')),
                ('fuel_efficiency', models.DecimalField(decimal_places=2, help_text='L per 100 km', max_digits=5)),
                ('has_wifi', models.BooleanField(default=False)),
                ('has_power_ports', models.BooleanField(default=True)),
                ('has_entertainment', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['manufacturer', 'model'],
            },
        ),
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('MAJOR', 'Major Carrier'), ('LOW_COST', 'Low Cost Carrier'), ('REGIONAL', 'Regional'), ('CHARTER', 'Charter')], default='MAJOR', max_length=20)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='airline_logos/')),
                ('website', models.URLField(blank=True)),
                ('baggage_allowance', models.IntegerField(default=23, help_text='Kg')),
                ('cabin_baggage', models.IntegerField(default=7, help_text='Kg')),
                ('loyalty_program', models.CharField(blank=True, max_length=100)),
                ('alliance', models.CharField(blank=True, choices=[('STAR', 'Star Alliance'), ('SKYTEAM', 'SkyTeam'), ('ONEWORLD', 'oneworld'), ('NONE', 'None')], default='NONE', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['code'], name='flights_air_code_0536a7_idx'), models.Index(fields=['type'], name='flights_air_type_6c7bd4_idx')],
            },
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('timezone', models.CharField(max_length=50)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('has_lounge', models.BooleanField(default=False)),
                ('has_wifi', models.BooleanField(default=True)),
                ('terminal_count', models.IntegerField(default=1)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['code'],
                'indexes': [models.Index(fields=['code'], name='flights_air_code_36cb2c_idx'), models.Index(fields=['city', 'country'], name='flights_air_city_e57452_idx')],
            },
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_number', models.CharField(max_length=10, unique=True)),
                ('departure_time', models.DateTimeField()),
                ('arrival_time', models.DateTimeField()),
                ('duration_minutes', models.IntegerField(help_text='Flight duration in minutes')),
                ('is_recurring', models.BooleanField(default=False)),
                ('recurring_days', models.CharField(blank=True, help_text='Comma-separated days', max_length=21)),
                ('recurring_end_date', models.DateTimeField(blank=True, null=True)),
                ('total_seats', models.IntegerField()),
                ('available_seats', models.IntegerField()),
                ('base_price_economy', models.DecimalField(decimal_places=2, max_digits=10)),
                ('base_price_business', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('base_price_first', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('DELAYED', 'Delayed'), ('BOARDING', 'Boarding'), ('DEPARTED', 'Departing'), ('IN_AIR', 'In Air'), ('ARRIVED', 'Arrived'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed')], default='SCHEDULED', max_length=20)),
                ('gate', models.CharField(blank=True, max_length=10)),
                ('terminal', models.CharField(blank=True, max_length=10)),
                ('baggage_claim', models.CharField(blank=True, max_length=10)),
                ('check_in_start', models.DateTimeField(blank=True, null=True)),
                ('check_in_end', models.DateTimeField(blank=True, null=True)),
                ('boarding_start', models.DateTimeField(blank=True, null=True)),
                ('boarding_end', models.DateTimeField(blank=True, null=True)),
                ('min_advance_booking', models.IntegerField(default=0, help_text='Minimum hours before departure')),
                ('max_advance_booking', models.IntegerField(default=365, help_text='Maximum days before departure')),
                ('refundable', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='flights', to='flights.aircraft')),
                ('airline', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='flights', to='flights.airline')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='arriving_flights', to='flights.airport')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='departing_flights', to='flights.airport')),
            ],
            options={
                'ordering': ['departure_time'],
            },
        ),
        migrations.CreateModel(
            name='FlightDelay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_departure', models.DateTimeField()),
                ('actual_departure', models.DateTimeField()),
                ('delay_minutes', models.IntegerField()),
                ('reason', models.CharField(choices=[('WEATHER', 'Weather'), ('TECHNICAL', 'Technical Issues'), ('AIR_TRAFFIC', 'Air Traffic Control'), ('CREW', 'Crew Availability'), ('SECURITY', 'Security'), ('OTHER', 'Other')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delays', to='flights.flight')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FlightPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cabin_class', models.CharField(choices=[('ECONOMY', 'Economy'), ('PREMIUM_ECONOMY', 'Premium Economy'), ('BUSINESS', 'Business'), ('FIRST', 'First')], max_length=20)),
                ('bucket_name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('available_seats', models.IntegerField()),
                ('days_before_departure_min', models.IntegerField()),
                ('days_before_departure_max', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_tiers', to='flights.flight')),
            ],
            options={
                'ordering': ['flight', 'cabin_class', 'price'],
            },
        ),
        migrations.CreateModel(
            name='FlightSeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.CharField(max_length=4)),
                ('seat_class', models.CharField(choices=[('ECONOMY', 'Economy'), ('PREMIUM_ECONOMY', 'Premium Economy'), ('BUSINESS', 'Business'), ('FIRST', 'First')], default='ECONOMY', max_length=20)),
                ('seat_type', models.CharField(choices=[('WINDOW', 'Window'), ('MIDDLE', 'Middle'), ('AISLE', 'Aisle'), ('EXTRA_LEG', 'Extra Legroom')], max_length=20)),
                ('is_available', models.BooleanField(default=True)),
                ('price_multiplier', models.DecimalField(decimal_places=2, default=1.0, max_digits=4)),
                ('has_power', models.BooleanField(default=False)),
                ('has_extra_legroom', models.BooleanField(default=False)),
                ('near_exit', models.BooleanField(default=False)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='flights.flight')),
            ],
        ),
        migrations.AddIndex(
            model_name='flight',
            index=models.Index(fields=['flight_number'], name='flights_fli_flight__794da4_idx'),
        ),
        migrations.AddIndex(
            model_name='flight',
            index=models.Index(fields=['origin', 'destination'], name='flights_fli_origin__ff1479_idx'),
        ),
        migrations.AddIndex(
            model_name='flight',
            index=models.Index(fields=['departure_time'], name='flights_fli_departu_5bc2af_idx'),
        ),
        migrations.AddIndex(
            model_name='flight',
            index=models.Index(fields=['status'], name='flights_fli_status_e6e528_idx'),
        ),
        migrations.AddIndex(
            model_name='flight',
            index=models.Index(fields=['origin', 'departure_time'], name='flights_fli_origin__efbfbc_idx'),
        ),
        migrations.AddIndex(
            model_name='flight',
            index=models.Index(fields=['destination', 'arrival_time'], name='flights_fli_destina_22dd17_idx'),
        ),
        migrations.AddIndex(
            model_name='flightdelay',
            index=models.Index(fields=['flight', 'created_at'], name='flights_fli_flight__ecfa9b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='flightpricing',
            unique_together={('flight', 'cabin_class', 'bucket_name')},
        ),
        migrations.AddIndex(
            model_name='flightseat',
            index=models.Index(fields=['flight', 'is_available'], name='flights_fli_flight__ab7725_idx'),
        ),
        migrations.AddIndex(
            model_name='flightseat',
            index=models.Index(fields=['seat_class'], name='flights_fli_seat_cl_44fc98_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='flightseat',
            unique_together={('flight', 'seat_number')},
        ),
    ]
